### ISSUE TITLE
TypeError: Request with GET/HEAD method cannot have body

### ISSUE THREAD

**Issue by bengavrilov** [castle/castle-node#122]
Here is how to reproduce:
```typescript
import { Castle } from '@castleio/sdk';
const castle = new Castle({ apiSecret: api_key });
const devices = await castle.getDevicesForUser({ user_id:  id });
```

I noticed a fix was already published in the `develop` branch. Any update on how long it may take to be released?

**Comment by cibergarri** [comment]
I have the same issue when calling  `castle.getDevice`

**Comment by cibergarri** [comment]
I think the issue is the release 1.0.3 has not been created yet @reneechar

**Comment by bartes** [comment]
Thank you for pointing that out 👍 . The 1.0.3 version should be available in the npm registry.

I'm closing the issue.  Please reopen or create the new one if you notice any problem with the fix.

**Comment by cibergarri** [comment]
Thank you @bartes!!
