### ISSUE TITLE
Consistency of failover policy actions

### ISSUE THREAD

**Issue by raiyansayeed** [castle/castle-node#134]
Hi there Castle team 😃 . Hope you're doing well. 

I'm not sure if this is a "bug" but nonetheless this issue has caused some issues in work I am currently involved with and may have affected others as well. 

Currently, I believe when an AbortError occurs during a [`castle.risk`](https://github.com/castle/castle-node/blob/b747d17de4f7b379db90a267d06c1f2e7b03c64f/src/api/services/api-risk.service.ts#L22) call, we get a result similar to the response expected (i.e there is a policy object within the failover response). However the [`castle.filter`](https://github.com/castle/castle-node/blob/b747d17de4f7b379db90a267d06c1f2e7b03c64f/src/api/services/api-filter.service.ts#L23) call does not appear to return the same. This may lead developers to have to handle these calls separately even though they should return similar responses.

Is there a specific reason for this difference? Currently my team and I have had to workaround these differences but ideally they would return a similar response (leaning towards the policy object method).

I was not able to find any documentation mentioning AbortError responses either. Would it make sense to add this possible response object to the README or Castle docs? 

Any info would be appreciated. Besides that, thank you for the awesome work you've done so far with this library!

**Comment by bartes** [comment]
hi @raiyansayeed. Thank you for pointing that out.

We have released the new version 2.0.0 which should cover the problem you mentioned. 🚀

Regarding AbortError: it is related to the timeout setting which you can find it in the configuration.

I'm closing this ticket now but don't hesitate to open the new one if you notice any further SDK problems.
